sudo: required

variables:
    docker_tag: tag-{{ timestamp }}
services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin hub.docker.com
  - echo "Docker Hub credentials are working"
    

install:
  - docker build -t philrumble/docker-test .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

jobs:
  include:
    - stage: install kubectl
      script:
        - |
          echo 'Installing kubectl';
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl;
          chmod +x ./kubectl;
          echo 'Installed kubectl';
          export TSTAMP=`date +"%Y%m%d%H%M%S"`
          echo "$TSTAMP"
