sudo: required

language: ruby

variables:
    docker_tag: tag-{{ timestamp }}
services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - echo "Docker Hub credentials are working"
    
jobs:
  include:
    - stage: build docker image
      script:
        - |
          echo "Building docker image";
          docker build . -t philrumble/docker-test:latest;
          docker push philrumble/docker-test:latest;


after_success:
    - export TAG=`date +"%Y%m%d%H%M%S"`
  - docker tag philrumble/docker-test:latest philrumble/docker-test:$TAG
  - docker push philrumble/docker-test
